version: "3"

services:
  web:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile.dev
    user: dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - gem_cache:/gems
    # we are using .env for our environment variables, which means we will need to add those to our project later
    env_file:
      - .env/development/database
      - .env/development/web
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'

    # Note: to run Procfile from bin/dev, you'll need to add
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    tty: true
    # Without the tty option set, the container will close the app after launching

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  gem_cache:
